Adding SimplifyVectorFilter and a DouglasPeuker simplification class. Also modified CmakeList because of a undefined reference to SimplifyWithPreserveTopology.